name: "ABC VPROFILE IAC"
on:
  push:
    branches:
      - main
      - stage
    paths:
      - terraform/**
  pull_request:
    branches:
      - main
    paths:
      - terraform/**

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  AWS_REGION: us-east-1
  AWS_EKS_CLUSTER: abc-fire

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v5

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.3"

      - name: "Terraform Init"
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: "Terraform format & check"
        id: fmt
        run: terraform fmt -check

      - name: "Terraform Validate"
        id: validate
        run: terraform validate

      - name: "Terraform Plan"
        id: plan
        run: terraform plan -no-color -input=false -out planfile
        continue-on-error: true

      - name: "Terraform Plan Check"
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: "Terraform Apply on Main"
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false -parallelism=1 planfile

      - name: "Config AWS creds"
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: "Get Kube config file"
        id: kube-config
        if: steps.apply.outcome == 'success'
        run: aws eks update-kubeconfig --region ${{env.AWS_REGION}} --name ${{env.AWS_EKS_CLUSTER}}

      - name: "Install Ingress controller"
        if: steps.apply.outcome == 'success' && steps.kube-config.outcome == 'success'
        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml
